#include"struct.h"
struct S_start start;
struct S_light light;
struct S_frog frog;
struct Z_sort z_sort;
struct S_cube cube[CUBE];
struct S_butterfly butterfly[BUTTERFLY];
struct S_me me;
struct S_ground ground;
struct S_sky sky;
struct S_cloud cloud[CLOUD];
struct S_tree tree[TREE];
struct S_grass grass[GRASS];
struct S_grass2 grass2[GRASS2];
struct S_screen screen;
struct S_me_effect me_effect[ME_EFFECT];
double time;
int img_catch;
int img_title;
int img_start[5];
int img_ground;
int img_butterfly[3];
int img_grass[3];
int img_grass2[5];
int img_tree[5];
int img_leaf[3];
int img_sky;
int img_cloud[5];
int sound_clash;
int sound_eat;
int sound_grass;
int mask1;
int mask2;
int score;